name: Deploy

on:
  push:
    branches: [main]

jobs:
  purge-cf-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl -s -X POST "https://api.cloudflare.com/client/v4/zones/3c8e89812c344f40fdbe931519f287af/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"purge_everything":true}'
